### PR TITLE
Send SDL from deployer to Optimism minichef

### PR DESCRIPTION
**Pull request by hannespfeiffer**
Sends ~185k SDL from the deployer account to the Optimism minichef, using the canocical Optimism bridge

### CODE REVIEW

**Review by mjdatadog — APPROVED** [review]
LGTM to test

**Comment by hannespfeiffer** [comment]
To test the workflow, the first transfer was executed with `0.000000000000001` SDL.

- `approve()` [transaction](0x589ec0de942ad7922187785b0c103104924699707467902a620c82bee2b9b589)
- `depositERC20TO()` [transaction](https://etherscan.io/tx/0xc6f376847899a4b7237fdc3adf0defe13464a10b97cb13878a2d04ca9b2fef7b)

Once the SDL show up on Optimism minichef, we can go ahead and send the full amount

**Comment by hannespfeiffer** [comment]
SDL [arrived](https://optimistic.etherscan.io/tx/0xc606ed90b6ce1fc3dc74b3813c4a57646fa9e720f701874b36aaa49abda7b7d8) on Optimism minichef.

**Review by mjdatadog — APPROVED** [review]

**Comment by hannespfeiffer** [comment]
The full amount of 184.67k SDL was succesfully sent to the Optimism bridge

- `approve()` [transaction](https://etherscan.io/tx/0x1d658f2a897c7b9a097bd8da632ef5f901f327c35bcc413890c1747e2080d723)
- `depositERC20To()` [transaction](https://etherscan.io/tx/0xd404a52ecdb18c8a947b9d417a5d6fa153e2ecb2c5502a279403c9c52a758bf4)

**Comment by hannespfeiffer** [comment]
184.67k SDL [arrived](https://optimistic.etherscan.io/tx/0x8cf05ccf186e9baa672991b7bfe0738cbbf1cdef7cddcdbc99753a67f98e7846) on Optimism Minichef

**Pull request merged**
