### PR TITLE
Add gauge votes and minichef updates for week 09_08__09_15, send 2_600_00 SDL for institutional support

### PR DESCRIPTION
**Pull request by hannespfeiffer**
- Snapshot [vote](https://snapshot.org/#/saddlefinance.eth/proposal/0xbd02291deb8b2156d0642b27049902f8e884b76b697202bd9f5bce5ac02c3f3b)
- Add gauge votes for week 09_08__09_15
- Add arbitrum and minichef updates for the same week
-  send 2_600_00 SDL for institutional support

### CODE REVIEW

**Review by penandlim — APPROVED** [review]
LGTM. We could add more tx in this nonce as well.

**Comment by penandlim** [comment]
```
Transaction was Mined 
---------------------
Tx Hash: 0x67e5e3a960d21a14eb1cfbc55775b9060647ec7617f4b90edd1af3cb94ad78f0
From: 0x0AF91FA049A7e1894F480bFE5bBa20142C6c29a9
To: 0x3F8E527aF4e0c6e763e8f368AC679c44C45626aE
Value: 0
Function: Gnosis Safe.execTransaction
Block: 15480971
Gas Used: 493686 / 535837 (92.1%)

Events In This Transaction
--------------------------
├── Vyper_contract (0x99Cb6c36816dE2131eF2626bb5dEF7E5cc8b9B14)
│   ├── NewGaugeWeight
│   │   ├── gauge_address: 0xB2Ac3382dA625eb41Fc803b57743f941a484e2a6
│   │   ├── time: 1662424888
│   │   ├── weight: 6830
│   │   └── total_weight: 10314000000000000000000
│   ├── NewGaugeWeight
│   │   ├── gauge_address: 0xc64F8A9fe7BabecA66D3997C9d15558BF4817bE3
│   │   ├── time: 1662424888
│   │   ├── weight: 749
│   │   └── total_weight: 9866000000000000000000
│   ├── NewGaugeWeight
│   │   ├── gauge_address: 0x953693DCB2E9DDC0c1398C1b540b81b63ceA5e16
│   │   ├── time: 1662424888
│   │   ├── weight: 782
│   │   └── total_weight: 9867000000000000000000
│   ├── NewGaugeWeight
│   │   ├── gauge_address: 0x104F44551386d603217450822443456229F73aE4
│   │   ├── time: 1662424888
│   │   ├── weight: 427
│   │   └── total_weight: 9894000000000000000000
│   ├── NewGaugeWeight
│   │   ├── gauge_address: 0x6EC5DD7D8E396973588f0dEFD79dCA04F844d57C
│   │   ├── time: 1662424888
│   │   ├── weight: 85
│   │   └── total_weight: 9880000000000000000000
│   ├── NewGaugeWeight
│   │   ├── gauge_address: 0x13Ba45c2B686c6db7C2E28BD3a9E8EDd24B894eD
│   │   ├── time: 1662424888
│   │   ├── weight: 86
│   │   └── total_weight: 9886000000000000000000
│   ├── NewGaugeWeight
│   │   ├── gauge_address: 0x9585a54297beAa83F044866678b13d388D0180bf
│   │   ├── time: 1662424888
│   │   ├── weight: 0
│   │   └── total_weight: 9459000000000000000000
│   ├── NewGaugeWeight
│   │   ├── gauge_address: 0x702c1b8Ec3A77009D5898e18DA8F8959B6dF2093
│   │   ├── time: 1662424888
│   │   ├── weight: 578
│   │   └── total_weight: 9589000000000000000000
│   ├── NewGaugeWeight
│   │   ├── gauge_address: 0x50d745c2a2918A47A363A2d32becd6BBC1A53ece
│   │   ├── time: 1662424888
│   │   ├── weight: 427
│   │   └── total_weight: 10016000000000000000000
│   ├── NewGaugeWeight
│   │   ├── gauge_address: 0x2683190e31e8ce47467c98ff1DBc018aCDD43C2f
│   │   ├── time: 1662424888
│   │   ├── weight: 2
│   │   └── total_weight: 9966000000000000000000
│   └── NewGaugeWeight
│       ├── gauge_address: 0x7B2025Bf8c5ee8Baad9da8C3E3Ee45E96ed8b8EA
│       ├── time: 1662424888
│       ├── weight: 33
│       └── total_weight: 9999000000000000000000
│   
├── Saddle DAO (0xf1Dc500FdE233A4055e25e5BbF516372BC4F6871)
│   └── Transfer
│       ├── from: 0x3F8E527aF4e0c6e763e8f368AC679c44C45626aE
│       ├── to: 0x17a069f6E16D8155568594e9539B0d8136c8a4Ae
│       └── value: 2600000000000000000000000
│   
└── Gnosis Safe (0x3F8E527aF4e0c6e763e8f368AC679c44C45626aE)
    └── ExecutionSuccess
        ├── txHash: 0x61dc9b6af8af8611d6cc6acc1f26ece5dcd6797c6697dc229062013769c5464c
        └── payment: 0

```

**Review by penandlim — CHANGES_REQUESTED** [review]
`massUpdatePools()` should be called prior to changing minichef rates. This will ensure to checkpoint any existing stakers.

**Comment by hannespfeiffer** [comment]
Optimism weights changed. 

```
Transaction sent: 0x64c93e1d4e329ac78dee9b773ea5460b4c9bfc091097d3f0f3382be3c1491354
  Gas price: 0.001 gwei   Gas limit: 130518   Nonce: 71
  MinichefV2.massUpdatePools confirmed   Block: 22324190   Gas used: 118653 (90.91%)

Transaction sent: 0xa29cc219034490dcb861ca41c2f68cb47a327c3601948f53542eb3ce1fcfc353
  Gas price: 0.001 gwei   Gas limit: 47905   Nonce: 72
  MinichefV2.set confirmed   Block: 22324193   Gas used: 43550 (90.91%)

Transaction sent: 0x65f46501de2456078e742f986c3c44c8d508d61b1477fcf71c1db50ad52085ff
  Gas price: 0.001 gwei   Gas limit: 41718   Nonce: 73
  MinichefV2.set confirmed   Block: 22324195   Gas used: 37926 (90.91%)

Transaction sent: 0xaa6ad41bea10f2ad1cadf82361887cfdf01435f95bc8334348ce347423f9e36e
  Gas price: 0.001 gwei   Gas limit: 47905   Nonce: 74
  MinichefV2.set confirmed   Block: 22324197   Gas used: 43550 (90.91%)

Transaction sent: 0xb03baa36ed11db31482be3f5e0c6050a9b45ab86dcfeddd92253c27a454d9571
  Gas price: 0.001 gwei   Gas limit: 47905   Nonce: 75
  MinichefV2.set confirmed   Block: 22324201   Gas used: 43550 (90.91%)

Transaction sent: 0xf7ddce86f55637f0d2f8c55edf9b6ea864cbabb6e9be68d360cf57cf2d4a79b6
  Gas price: 0.001 gwei   Gas limit: 47878   Nonce: 76
  MinichefV2.set confirmed   Block: 22324206   Gas used: 43526 (90.91%)

Transaction sent: 0xdbaa1854a68c2ad91ae0b873e78cd80712dada9c51fbd1dc96f67a6b76d0d8ce
  Gas price: 0.001 gwei   Gas limit: 47905   Nonce: 77
  MinichefV2.set confirmed   Block: 22324210   Gas used: 43550 (90.91%)

358614004629629632
Transaction sent: 0x36188bed774e55e65ad7cf9ced8a36e375397c0c03c3b3b45eec69a35cea0c7e
  Gas price: 0.001 gwei   Gas limit: 32778   Nonce: 78
  MinichefV2.setSaddlePerSecond confirmed   Block: 22324215   Gas used: 29799 (90.91%)

358614004629629632
```

**Comment by hannespfeiffer** [comment]
Arbitrum weights changed (via TransactionBuilder)

https://gnosis-safe.io/app/arb1:0x8e6e84DDab9d13A17806d34B097102605454D147/transactions/history

**Pull request merged**
